# Generated by Django 3.0.7 on 2020-12-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=50)),
                ('tweet_text', models.CharField(max_length=600)),
                ('created_at', models.DateTimeField()),
                ('sentiment', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
