# Generated by Django 4.1.3 on 2022-11-13 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Crawl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tweet_id", models.CharField(max_length=50)),
                ("tweet_text", models.CharField(max_length=600)),
                ("created_at", models.DateTimeField()),
                (
                    "sentiment",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TweetSentiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tweet_id", models.CharField(max_length=50)),
                ("text", models.TextField()),
                ("media", models.JSONField(blank=True, null=True)),
                ("created_at", models.CharField(max_length=255)),
                (
                    "point",
                    models.IntegerField(
                        choices=[(-1, "NEGATIVE"), (0, "NEUTRAL"), (1, "POSITIVE")],
                        default=0,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
