# Generated by Django 4.1.3 on 2022-11-13 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crawl", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TweetSentiment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tweet_id", models.CharField(max_length=50)),
                ("text", models.TextField()),
                ("media_key", models.CharField(blank=True, max_length=255, null=True)),
                ("media_type", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.CharField(max_length=255)),
                (
                    "point",
                    models.IntegerField(
                        choices=[(-1, "NEGATIVE"), (0, "NEUTRAL"), (1, "POSITIVE")],
                        default=0,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
