# Generated by Django 3.0.7 on 2020-12-06 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(default=None, max_length=255)),
                ('tweet_text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positif', models.IntegerField(default=0)),
                ('negatif', models.IntegerField(default=0)),
                ('netral', models.IntegerField(default=0)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_sentimen', to='history.History')),
            ],
        ),
    ]
