# Generated by Django 3.0.7 on 2020-12-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='tweet_id',
            field=models.CharField(max_length=50),
        ),
    ]
