# Generated by Django 3.1.4 on 2020-12-26 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20201206_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='history',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='history_sentimen', to='history.history'),
        ),
    ]
