# Generated by Django 3.0.7 on 2021-03-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20201226_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='tweet_text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
